"use client";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import WhatsAppButton from "@/components/WhatsAppButton";
import { motion } from "framer-motion";
import styles from "../privacy/LegalPage.module.css";

export default function TermsOfServicePage() {
    const lastUpdated = "June 3, 2026";
    
    return (
        <main style={{ position: "relative" }}>
            <Navbar />
            
            <section className={styles.hero}>
                <div className={styles.container}>
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.6 }}
                        className={styles.centerText}
                    >
                        <span className="section-label">Agreement</span>
                        <h1 className={styles.title}>Terms & Conditions</h1>
                        <p className={styles.subtitle}>
                            Last Updated: {lastUpdated} · Governed by the Indian Contract Act, 1872 and Information Technology Act, 2000.
                        </p>
                    </motion.div>
                </div>
            </section>

            <section className={styles.contentSection}>
                <motion.div 
                    className={styles.card}
                    initial={{ opacity: 0, y: 30 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6, delay: 0.1 }}
                >
                    {/* 1. Terms Acceptance */}
                    <div className={styles.block}>
                        <h2 className={styles.secTitle}>1. Acceptance of Terms</h2>
                        <p className={styles.secText}>
                            By accessing, browsing, or using the website of <strong>Gill Tech Solutions India</strong> (referred to as "Company", "we", "us", or "our"), you agree to be bound by these Terms and Conditions and all applicable laws and regulations of India. If you do not agree with any of these terms, you are prohibited from using or accessing this site.
                        </p>
                        <p className={styles.secText}>
                            This document is an electronic record in terms of the <strong>Information Technology Act, 2000</strong> and rules thereunder, and is generated by a computer system and does not require physical or digital signatures.
                        </p>
                    </div>

                    {/* 2. Services Outline */}
                    <div className={styles.block}>
                        <h2 className={styles.secTitle}>2. Services Provided</h2>
                        <p className={styles.secText}>
                            Gill Tech Solutions India provides custom software engineering consulting, application development, cloud DevOps services, and technical support. Any estimations, discovery calls, or project quotes provided through our website are preliminary assessments and do not constitute a legally binding service contract. Binding agreements are executed separately in physical or digital project service contracts with clients.
                        </p>
                    </div>

                    {/* 3. Intellectual Property */}
                    <div className={styles.block}>
                        <h2 className={styles.secTitle}>3. Intellectual Property Rights</h2>
                        <p className={styles.secText}>
                            Unless otherwise stated, all materials on this website, including but not limited to typography, code snippets, visual designs, images, brand names, and logos, are the intellectual property of Gill Tech Solutions India (under the proprietorship of Sumit Gill) and are protected by applicable copyright, trademark, and other intellectual property laws of India.
                        </p>
                        <p className={styles.secText}>
                            You may not republish, reproduce, copy, distribute, or commercially exploit any content from this website without explicit written consent from us.
                        </p>
                    </div>

                    {/* 4. Acceptable Use Policy */}
                    <div className={styles.block}>
                        <h2 className={styles.secTitle}>4. User Representation and Acceptable Use</h2>
                        <p className={styles.secText}>
                            By submitting a consultation request or contacting us, you represent and warrant that:
                        </p>
                        <ul className={styles.list}>
                            <li className={styles.listItem}>All information submitted by you is true, accurate, and current.</li>
                            <li className={styles.listItem}>You have the legal capacity to agree to these Terms.</li>
                            <li className={styles.listItem}>You will not use the contact form or website systems for any illegal, unauthorized, or spamming activities.</li>
                            <li className={styles.listItem}>You will not upload or transmit any viruses, malicious code, or files designed to disrupt the server infrastructure.</li>
                        </ul>
                    </div>

                    {/* 5. Limitation of Liability */}
                    <div className={styles.block}>
                        <h2 className={styles.secTitle}>5. Disclaimer and Limitation of Liability</h2>
                        <p className={styles.secText}>
                            The materials and contents on this website are provided on an "as is" and "as available" basis. Gill Tech Solutions India makes no warranties, expressed or implied, regarding the accuracy, complete reliability, or availability of the website or its contents.
                        </p>
                        <p className={styles.secText}>
                            Under no circumstances shall Gill Tech Solutions India, its proprietor Sumit Gill, or its developers be liable for any damages (including direct, indirect, incidental, or consequential damages) arising out of the use or inability to use the materials on this site, even if notified of the possibility of such damage.
                        </p>
                    </div>

                    {/* 6. Indemnification */}
                    <div className={styles.block}>
                        <h2 className={styles.secTitle}>6. Indemnification</h2>
                        <p className={styles.secText}>
                            You agree to indemnify, defend, and hold harmless Gill Tech Solutions India and its proprietor, officers, and contractors from and against any claims, liabilities, losses, damages, or costs (including reasonable legal fees) arising from your breach of these Terms, misuse of the website, or violation of third-party rights.
                        </p>
                    </div>

                    {/* 7. Governing Law and Jurisdiction */}
                    <div className={styles.block}>
                        <h2 className={styles.secTitle}>7. Governing Law and Dispute Resolution</h2>
                        <p className={styles.secText}>
                            These Terms and Conditions are governed by and construed in accordance with the laws of the Republic of India. 
                        </p>
                        <p className={styles.secText}>
                            Any dispute, claim, or controversy arising out of or relating to these Terms, including the determination of the scope or applicability of this agreement, shall be settled through mutual negotiation. If unresolved, disputes shall be subject to the exclusive jurisdiction of the competent courts of <strong>Bathinda, Punjab, India</strong>.
                        </p>
                    </div>

                    {/* 8. Modifications to Terms */}
                    <div className={styles.block}>
                        <h2 className={styles.secTitle}>8. Amendments and Updates</h2>
                        <p className={styles.secText}>
                            We reserve the right to revise or update these Terms & Conditions at any time without prior notice. By continuing to access our website after modifications are published, you agree to be bound by the updated terms. We recommend checking this page periodically to stay informed of any changes.
                        </p>
                    </div>

                    {/* 9. Contact Info */}
                    <div className={styles.block}>
                        <h2 className={styles.secTitle}>9. Contact Us</h2>
                        <p className={styles.secText}>
                            If you have any questions or feedback regarding these Terms and Conditions, please contact us:
                        </p>
                        <div className={styles.officerCard}>
                            <div className={styles.officerTitle}>Gill Tech Solutions India</div>
                            <div className={styles.officerText}><strong>Proprietor:</strong> Sumit Gill</div>
                            <div className={styles.officerText}><strong>Email:</strong> contact@gilltechsolutionsindia.info</div>
                            <div className={styles.officerText}><strong>Address:</strong> Bathinda, Punjab, India</div>
                        </div>
                    </div>
                </motion.div>
            </section>
            
            <Footer />
            <WhatsAppButton />
        </main>
    );
}
